### PR TITLE
Require qt6-quick3d

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin please rerender

### CODE REVIEW

**Review by mmcauliffe — APPROVED** [review]
LGTM, thanks for this, was just about to create a PR for it

**Comment by hmaarrfk** [comment]
So according to the Qt documentation this sh9uod be available under LPGL as well. 

Could we make Quick3D optional? Is that an option?

**Comment by jschueller** [comment]
oh yes, that would bits of it GPL for Qt6Quick3DSpatialAudio
maybe it clearer to drop the GPL bits then

**Comment by hmaarrfk** [comment]
We could also add ignore run export and if the library is still usable, then that would appease my concerns

**Pull request merged**
